### PR TITLE
firefox extension

### PR DESCRIPTION
**Pull request by OEmiliatanO**

### CODE REVIEW

**Comment by OEmiliatanO** [comment]
pack the files in firefox into a .zip file, and use firefox URL "about:debugging" to temporarily load the extension. however it come up an error: "TypeError: NetworkError when attempting to fetch resource.    tf.min.js:17:185424"

**Comment by scc-tw** [comment]
> pack the files in firefox into a .zip file, and use firefox URL "about:debugging" to temporarily load the extension. however it come up an error: "TypeError: NetworkError when attempting to fetch resource. tf.min.js:17:185424"

How to fix that error?

**Comment by OEmiliatanO** [comment]
i found that it's the problem of CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). 
add the code below into manifest.js can solve the problem
`"permissions": [
		"https://ernestchu.github.io/nsysu-captcha-solver/assets/model_tfjs/model.json"
	],`

**Comment by scc-tw** [comment]
LGTM. Thanks.

**Pull request merged**
